'use client';
import Link from 'next/link';
import { useEffect,useMemo,useState } from 'react';
import { PRODUCTS,rupiah } from '../catalog';
const labels={pending:'Menunggu pembayaran',paid:'Sudah bayar',processing:'Diproses',shipped:'Dikirim',completed:'Selesai',cancelled:'Dibatalkan'};

export default function AdminClient(){
 const [auth,setAuth]=useState(null),[tab,setTab]=useState('orders'),[orders,setOrders]=useState([]),[products,setProducts]=useState(PRODUCTS),[loading,setLoading]=useState(true),[error,setError]=useState(''),[query,setQuery]=useState(''),[filter,setFilter]=useState('all');
 async function load(){setLoading(true);try{const [or,pr]=await Promise.all([fetch('/api/orders',{cache:'no-store'}),fetch('/api/products',{cache:'no-store'})]);if(or.status===401){setAuth(false);return}const od=await or.json(),pd=await pr.json();if(!or.ok)throw new Error(od.error);const localOrders=JSON.parse(localStorage.getItem('ruloxius_orders')||'[]'),savedProducts=JSON.parse(localStorage.getItem('ruloxius_products')||'null'),localProducts=savedProducts?.some(p=>p.id==='2x1000ml'||p.id==='4x1000ml')?null:savedProducts;setOrders(od.orders?.length?od.orders:localOrders);setProducts(pd.mode==='demo'&&localProducts?localProducts:(pd.products||PRODUCTS));setAuth(true)}catch(e){setError(e.message||'Gagal memuat data.');setAuth(false)}finally{setLoading(false)}}
 useEffect(()=>{load()},[]);
 const shown=useMemo(()=>orders.filter(o=>(filter==='all'||o.status===filter)&&`${o.order_number} ${o.customer_name} ${o.phone}`.toLowerCase().includes(query.toLowerCase())),[orders,query,filter]);
 const metrics=useMemo(()=>({total:orders.length,newOrders:orders.filter(o=>o.status==='pending').length,revenue:orders.filter(o=>!['cancelled','pending'].includes(o.status)).reduce((s,o)=>s+(o.total||0),0)}),[orders]);
 async function change(order,status){const next=orders.map(o=>o.order_number===order.order_number?{...o,status}:o);setOrders(next);localStorage.setItem('ruloxius_orders',JSON.stringify(next));await fetch('/api/orders',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:order.id,status})})}
 async function saveProduct(product){setError('');const r=await fetch('/api/products',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify(product)}),d=await r.json();if(!r.ok){setError(d.error||'Gagal menyimpan produk');return false}const next=products.map(p=>p.id===product.id?{...product}:p);setProducts(next);localStorage.setItem('ruloxius_products',JSON.stringify(next));return true}
 if(auth===null)return <div className="app-page"><div className="empty">Memeriksa sesi admin…</div></div>;
 if(!auth)return <Login error={error} onLogin={load}/>;
 return <div className="app-page"><AdminHeader onLogout={async()=>{await fetch('/api/admin/session',{method:'DELETE'});setAuth(false)}}/><div className="admin-shell"><div className="admin-title"><small>CONTROL PANEL PEMILIK</small><h1>{tab==='orders'?'Kelola pesanan':'Kelola produk'}</h1><p>{tab==='orders'?'Pantau order dan proses pengiriman.':'Ubah foto, harga, stok, dan informasi produk tanpa coding.'}</p></div><nav className="admin-tabs"><button className={tab==='orders'?'active':''} onClick={()=>setTab('orders')}>Pesanan <b>{metrics.newOrders}</b></button><button className={tab==='products'?'active':''} onClick={()=>setTab('products')}>Produk</button></nav>{error?<p className="notice">{error}</p>:null}{tab==='orders'?<OrdersPanel loading={loading} metrics={metrics} shown={shown} query={query} setQuery={setQuery} filter={filter} setFilter={setFilter} change={change}/>:<ProductsPanel products={products} onSave={saveProduct}/>}</div></div>;
}
function AdminHeader({onLogout}){return <header className="simple-header"><Link className="brand brand-logo" href="/"><img src="/images/ruloxius-logo-v2.png" alt="RULOXIUS Home Care"/></Link><button className="btn btn-outline" onClick={onLogout}>Keluar</button></header>}
function OrdersPanel({loading,metrics,shown,query,setQuery,filter,setFilter,change}){return <><div className="metric-grid"><article><small>TOTAL ORDER</small><b>{metrics.total}</b></article><article><small>ORDER BARU</small><b>{metrics.newOrders}</b></article><article><small>PENDAPATAN</small><b>{rupiah(metrics.revenue)}</b></article></div><div className="admin-toolbar"><input placeholder="Cari nomor, nama, telepon…" value={query} onChange={e=>setQuery(e.target.value)}/><select value={filter} onChange={e=>setFilter(e.target.value)}><option value="all">Semua status</option>{Object.entries(labels).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></div><div className="panel">{loading?<div className="empty">Memuat order…</div>:shown.length?<table className="orders-table"><thead><tr><th>ORDER</th><th>PELANGGAN</th><th>ITEM</th><th>TOTAL</th><th>PEMBAYARAN</th><th>STATUS</th></tr></thead><tbody>{shown.map(o=><tr key={o.order_number}><td><b>{o.order_number}</b><br/><small>{new Date(o.created_at).toLocaleString('id-ID')}</small></td><td><b>{o.customer_name}</b><br/><small>{o.phone}</small></td><td>{(o.items||[]).map(i=><div key={i.id}>{i.size} × {i.quantity}</div>)}</td><td><b>{rupiah(o.total||0)}</b></td><td>{o.payment_method?.toUpperCase()}</td><td><select value={o.status} onChange={e=>change(o,e.target.value)}>{Object.entries(labels).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></td></tr>)}</tbody></table>:<div className="empty"><h3>Belum ada order</h3><p>Order baru akan muncul di sini.</p></div>}</div></>}
function ProductsPanel({products,onSave}){return <div className="admin-products">{products.map(p=><ProductEditor key={p.id} product={p} onSave={onSave}/>)}</div>}
function ProductEditor({product,onSave}){const [form,setForm]=useState(product),[busy,setBusy]=useState(false),[saved,setSaved]=useState(false);const set=(k,v)=>setForm(f=>({...f,[k]:v}));function photo(e){const file=e.target.files?.[0];if(!file)return;if(file.size>1000000)return alert('Foto maksimal 1 MB');const reader=new FileReader();reader.onload=()=>set('image',reader.result);reader.readAsDataURL(file)}async function submit(e){e.preventDefault();setBusy(true);setSaved(await onSave(form));setBusy(false);setTimeout(()=>setSaved(false),2500)}return <form className="panel product-editor" onSubmit={submit}><div className="editor-photo"><img src={form.image} alt={form.size}/><label>Ganti foto<input type="file" accept="image/jpeg,image/png,image/webp" onChange={photo}/></label></div><div className="editor-fields"><div className="form-grid"><Field label="Nama paket"><input value={form.name} onChange={e=>set('name',e.target.value)} required/></Field><Field label="Ukuran"><input value={form.size} onChange={e=>set('size',e.target.value)} required/></Field><Field label="Harga jual"><input type="number" value={form.price} onChange={e=>set('price',Number(e.target.value))} required/></Field><Field label="Harga coret"><input type="number" value={form.compareAt} onChange={e=>set('compareAt',Number(e.target.value))}/></Field><Field label="Stok"><input type="number" value={form.stock??0} onChange={e=>set('stock',Number(e.target.value))}/></Field><Field label="Nominal hemat"><input type="number" value={form.saving} onChange={e=>set('saving',Number(e.target.value))}/></Field><Field label="Isi paket" full><input value={form.detail} onChange={e=>set('detail',e.target.value)}/></Field><Field label="Keterangan harga" full><input value={form.unit} onChange={e=>set('unit',e.target.value)}/></Field></div><label className="admin-check"><input type="checkbox" checked={!!form.popular} onChange={e=>set('popular',e.target.checked)}/> Tandai sebagai paling laris</label><button disabled={busy} className="btn btn-primary">{busy?'MENYIMPAN…':saved?'TERSIMPAN ✓':'SIMPAN PERUBAHAN'}</button></div></form>}
function Field({label,full,children}){return <label className={`field ${full?'full':''}`}><span>{label}</span>{children}</label>}
function Login({onLogin,error:initialError}){const [error,setError]=useState(initialError||''),[busy,setBusy]=useState(false);async function submit(e){e.preventDefault();setBusy(true);const pin=new FormData(e.currentTarget).get('pin'),r=await fetch('/api/admin/session',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({pin})}),d=await r.json();setBusy(false);if(!r.ok)return setError(d.error||'Login gagal.');await onLogin()}return <div className="app-page"><div className="checkout-shell"><form onSubmit={submit} className="panel admin-login"><div className="brand"><span>RULOXIUS</span><small>OWNER PANEL</small></div><h1>Masuk pemilik</h1><p>Gunakan PIN privat yang tersimpan di server.</p><div className="field"><label>PIN admin</label><input name="pin" type="password" required autoFocus/></div>{error?<p className="notice">{error}</p>:null}<button disabled={busy} className="btn btn-primary submit-order">{busy?'MEMERIKSA…':'MASUK CONTROL PANEL'}</button></form></div></div>}
