import { createHash } from 'node:crypto';
import { cookies } from 'next/headers';
import { NextResponse } from 'next/server';
import { PRODUCTS } from '../../catalog';

const URL=process.env.NEXT_PUBLIC_SUPABASE_URL,KEY=process.env.SUPABASE_SERVICE_ROLE_KEY;
const isAdmin=async()=>{const pin=process.env.ADMIN_PIN||(process.env.NODE_ENV!=='production'?'2026':undefined);if(!pin)return false;return (await cookies()).get('ruloxius_admin')?.value===createHash('sha256').update(`ruloxius:${pin}`).digest('hex')};
const map=p=>({id:p.id,name:p.name,size:p.size,detail:p.description||p.detail,price:Number(p.price),compareAt:Number(p.compare_at??p.compareAt??p.price),saving:Number(p.saving||0),unit:p.unit||'',image:p.image_url||p.image,popular:Boolean(p.popular),active:p.active!==false,stock:Number(p.stock??0)});

export async function GET(){if(!URL||!KEY)return NextResponse.json({products:PRODUCTS,mode:'demo'});const r=await fetch(`${URL}/rest/v1/products?select=*&active=eq.true&order=price.asc`,{headers:{apikey:KEY,Authorization:`Bearer ${KEY}`},cache:'no-store'});if(!r.ok)return NextResponse.json({error:'Gagal memuat produk'},{status:500});return NextResponse.json({products:(await r.json()).map(map),mode:'supabase'})}
export async function PUT(request){if(!await isAdmin())return NextResponse.json({error:'Tidak diizinkan'},{status:401});const body=await request.json();if(!body.id||!body.name||!body.size||Number(body.price)<0)return NextResponse.json({error:'Data produk tidak valid'},{status:400});if((body.image||'').length>1500000)return NextResponse.json({error:'Foto maksimal sekitar 1 MB'},{status:400});if(!URL||!KEY)return NextResponse.json({product:body,mode:'demo'});const record={name:body.name,size:body.size,description:body.detail,price:Number(body.price),compare_at:Number(body.compareAt||body.price),saving:Number(body.saving||0),unit:body.unit||'',image_url:body.image,stock:Number(body.stock||0),popular:Boolean(body.popular),active:body.active!==false};const r=await fetch(`${URL}/rest/v1/products?id=eq.${encodeURIComponent(body.id)}`,{method:'PATCH',headers:{apikey:KEY,Authorization:`Bearer ${KEY}`,'Content-Type':'application/json',Prefer:'return=representation'},body:JSON.stringify(record)});if(!r.ok)return NextResponse.json({error:'Gagal menyimpan produk'},{status:500});return NextResponse.json({product:map((await r.json())[0]),mode:'supabase'})}
