'use client';
import Link from 'next/link';
import { useSearchParams } from 'next/navigation';
import { useEffect, useMemo, useState } from 'react';
import { PRODUCTS, rupiah } from '../catalog';

const WA='6281382920207';
const SHOPEE=process.env.NEXT_PUBLIC_SHOPEE_URL||'https://s.shopee.co.id/2qSqzbiP1J';
export default function CheckoutClient(){
 const params=useSearchParams(),qrisUrl=process.env.NEXT_PUBLIC_QRIS_IMAGE_URL;
 const [products,setProducts]=useState(PRODUCTS);
 useEffect(()=>{(async()=>{try{const r=await fetch('/api/products'),d=await r.json(),saved=JSON.parse(localStorage.getItem('ruloxius_products')||'null'),local=saved?.some(p=>p.id==='2x1000ml'||p.id==='4x1000ml')?null:saved;setProducts(d.mode==='demo'&&local?local:(d.products||PRODUCTS))}catch{}})()},[]);
 const cart=useMemo(()=>{try{return JSON.parse(params.get('cart')||'{"500ml":1}')}catch{return {'500ml':1}}},[params]);
 const items=products.filter(p=>cart[p.id]>0).map(p=>({...p,quantity:cart[p.id]}));
 const subtotal=items.reduce((sum,p)=>sum+p.price*p.quantity,0);
 const [payment,setPayment]=useState('qris'),[proof,setProof]=useState(''),[state,setState]=useState({loading:false,error:'',order:null});
 async function submit(e){e.preventDefault();if(payment==='shopee'){window.open(SHOPEE,'_blank','noopener,noreferrer');return}const fd=new FormData(e.currentTarget);if(!items.length)return setState({loading:false,error:'Pilih minimal satu produk.',order:null});setState({loading:true,error:'',order:null});const payload={customer_name:fd.get('name'),phone:fd.get('phone'),address:fd.get('address'),city:fd.get('city'),postal_code:fd.get('postal'),notes:fd.get('notes'),payment_method:payment,payment_proof:proof,items:items.map(({id,name,size,price,quantity})=>({id,name,size,price,quantity})),subtotal,total:subtotal,source:'website'};try{const response=await fetch('/api/orders',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});const data=await response.json();if(!response.ok)throw new Error(data.error||'Pesanan gagal disimpan');const order={...payload,...data,created_at:new Date().toISOString(),status:'pending'};const local=JSON.parse(localStorage.getItem('ruloxius_orders')||'[]');localStorage.setItem('ruloxius_orders',JSON.stringify([order,...local]));setState({loading:false,error:'',order});if(window.fbq)window.fbq('track','Purchase',{value:subtotal,currency:'IDR'});if(window.ttq)window.ttq.track('CompletePayment',{value:subtotal,currency:'IDR'});window.scrollTo({top:0,behavior:'smooth'})}catch(err){setState({loading:false,error:err.message,order:null})}}
 function upload(e){const file=e.target.files?.[0];if(!file)return;if(file.size>1500000)return setState(s=>({...s,error:'Ukuran bukti maksimal 1,5 MB.'}));const reader=new FileReader();reader.onload=()=>setProof(reader.result);reader.readAsDataURL(file)}
 const waText=state.order?encodeURIComponent(`ORDER RULOXIUS BARU\n\nNomor: ${state.order.order_number}\nNama: ${state.order.customer_name}\nProduk: ${state.order.items.map(i=>`${i.size} x ${i.quantity}`).join(', ')}\nTotal: ${rupiah(subtotal)}\nAlamat: ${state.order.address}, ${state.order.city} ${state.order.postal_code}\nPembayaran: ${state.order.payment_method.toUpperCase()}\n\nMohon dikonfirmasi.`):'';
 if(state.order)return <div className="app-page"><SimpleHeader/><div className="checkout-shell"><div className="panel checkout-success"><div className="success-check">✓</div><h1>Pesanan berhasil dibuat</h1><p>Nomor pesanan Anda</p><h2>{state.order.order_number}</h2><p className="notice success">Pesanan sudah tercatat. Kirim konfirmasi melalui WhatsApp agar tim kami segera memeriksa pembayaran.</p><a className="btn btn-wa" target="_blank" rel="noopener noreferrer" href={`https://wa.me/${WA}?text=${waText}`}>KONFIRMASI VIA WHATSAPP</a><br/><br/><Link href="/">Kembali ke beranda</Link></div></div></div>;
 return <div className="app-page"><SimpleHeader/><form className="checkout-shell" onSubmit={submit}><div className="checkout-title"><small>CHECKOUT AMAN</small><h1>Selesaikan pesanan</h1><p>Isi data penerima dan pilih metode pembayaran.</p></div><div className="checkout-layout"><div><CustomerFields/><section className="panel payment-panel"><h2>2. Metode pembayaran</h2><div className="payment-options">{[['qris','▦ QRIS','Scan dengan aplikasi pembayaran'],['transfer','▤ Transfer Bank','Tersedia Bank BRI dan Mandiri'],['cod','◫ COD','Boleh bayar saat barang diterima'],['shopee','🛍 Shopee','Checkout melalui toko resmi']].map(([id,title,desc])=><label key={id} className={`pay-option ${payment===id?'active':''}`}><input type="radio" name="payment" value={id} checked={payment===id} onChange={()=>setPayment(id)}/><span><b>{title}</b><br/><small>{desc}</small></span></label>)}</div>{payment==='qris'?<>{qrisUrl?<img className="qris-image" src={qrisUrl} alt="QRIS resmi RULOXIUS"/>:<div className="qr-placeholder"><span>QRIS MERCHANT<br/>BELUM DIATUR</span></div>}<p className="notice">{qrisUrl?'Scan QRIS resmi lalu upload bukti pembayaran.':'Masukkan URL gambar QRIS resmi pada NEXT_PUBLIC_QRIS_IMAGE_URL sebelum menerima pembayaran.'}</p></>:null}{payment==='transfer'?<p className="notice success"><b>Transfer tersedia melalui Bank BRI dan Bank Mandiri.</b><br/>Nomor rekening resmi akan dikirim admin melalui WhatsApp setelah order dibuat.</p>:null}{payment==='cod'?<p className="notice success"><b>COD tersedia.</b> Anda dapat membayar saat barang diterima.</p>:null}{payment==='shopee'?<p className="notice success">Anda akan diarahkan ke produk RULOXIUS di Shopee.</p>:null}{payment!=='shopee'?<div className="proof-upload"><b>Upload bukti pembayaran</b><p><small>JPG/PNG, maksimal 1,5 MB. Bisa dilewati untuk COD.</small></p><input type="file" accept="image/jpeg,image/png" onChange={upload}/>{proof?<p className="notice success">Bukti siap dikirim ✓</p>:null}</div>:null}</section></div><OrderSummary items={items} subtotal={subtotal} state={state} payment={payment}/></div></form></div>;
}
function CustomerFields(){return <section className="panel"><h2>1. Data penerima</h2><div className="form-grid"><Field name="name" label="Nama lengkap" required/><Field name="phone" label="Nomor WhatsApp" type="tel" required/><Field name="address" label="Alamat lengkap" full textarea required/><Field name="city" label="Kota / Kabupaten" required/><Field name="postal" label="Kode pos" required/><Field name="notes" label="Catatan untuk penjual (opsional)" full textarea/></div></section>}
function OrderSummary({items,subtotal,state,payment}){return <aside><section className="panel"><h2>Ringkasan pesanan</h2>{items.length?items.map(item=><div className="order-row" key={item.id}><b>{item.size} × {item.quantity}</b><strong>{rupiah(item.price*item.quantity)}</strong><small>{item.name}</small></div>):<p>Keranjang kosong.</p>}<div className="summary-total"><span>Total</span><span>{rupiah(subtotal)}</span></div>{state.error?<p className="notice">{state.error}</p>:null}<button disabled={state.loading} className="btn btn-primary submit-order">{state.loading?'MENYIMPAN...':payment==='shopee'?'LANJUT KE SHOPEE':'BUAT PESANAN'}</button><p className="checkout-terms">Dengan memesan, Anda menyetujui data digunakan untuk memproses dan mengirim pesanan.</p></section></aside>}
function SimpleHeader(){return <header className="simple-header"><Link className="brand brand-logo" href="/"><img src="/images/ruloxius-logo-v2.png" alt="RULOXIUS Home Care"/></Link><Link href="/">← Kembali belanja</Link></header>}
function Field({label,full,textarea,...props}){return <div className={`field ${full?'full':''}`}><label htmlFor={props.name}>{label}</label>{textarea?<textarea id={props.name} rows="3" {...props}/>:<input id={props.name} {...props}/>}</div>}
